---
sudo: required
dist: trusty
language: python
python:
  - "2.7"
services: docker
script: ./docker_build
after_success:
  - pip install pyyaml coveralls
  - docker cp ingredient-phrase-tagger-container:$(docker exec -it ingredient-phrase-tagger-container bash -c "ls -a .coverage.*") ./
  - coverage combine
  - coveralls
