---
sudo: required
services: docker
script: ./docker_build
after_success:
  - pip install pyyaml coveralls
  # Fix paths in .coverage so they match Coveralls' expectations of Travis'
  # paths.
  - sed -i "s@\"/app/@\"${PWD}/@g" .coverage
  - coveralls
